### ISSUE TITLE
Document types are generated on the fly when running tests

### ISSUE THREAD

**Issue by ChrisBAshton** [alphagov/content-publisher#1686]
Every time we run `build(:document_type)`, this generates a fake document type, which is not removed once the test is complete. This means that after a few tests have run, we have a number of randomly generated document types existing in memory.

This is not particularly clean and it risks our tests passing when they shouldn't (or failing when they should) as we're not operating against a pure environment. It also led to [issues when trying to incorporate i18n](https://github.com/alphagov/content-publisher/pull/1659#discussion_r369422812).

We should investigate to see if we could implement some sort of self-cleanup at the end of each test run.

**Comment by benthorner** [comment]
Thanks for raising this @ChrisBAshton! I think we should consider moving this to our "Wall of Pain", so we can think about addressing/prioritising it alongside the other cards there.

**Comment by ChrisBAshton** [comment]
Raised https://trello.com/c/aZ8R716k/1436-document-types-are-generated-on-the-fly-when-running-tests
