### ISSUE TITLE
Bug with the topic checkboxes

### ISSUE THREAD

**Issue by simonwhatley** [alphagov/content-publisher#2154]
When selecting a topic the check marks in the checkboxes are small and misaligned:

<img width="684" alt="Screenshot 2020-09-08 at 11 33 59" src="https://user-images.githubusercontent.com/23444/92582019-56906880-f288-11ea-8ebc-3946576065c6.png">

**Comment by kevindew** [comment]
Thanks for the report, I believe this will be fixed when we upgrade [miller-columns-element](https://github.com/alphagov/miller-columns-element) - I'll try get that sorted and pushed out in the next day or two.

**Comment by kevindew** [comment]
This is now resolved:

![Screenshot 2020-09-15 at 10 50 34](https://user-images.githubusercontent.com/282717/93195621-5dfcb980-f741-11ea-9c8d-ec111164b3ff.png)
