### ISSUE TITLE
Cope when we get errors from S3

### ISSUE THREAD

**Issue by benthorner** [alphagov/content-publisher#298]
At the moment we don't catch errors if something goes wrong we we interact with our S3 bucket.

   * `app/services/image_uploader.rb` (creating the blob)
   * `app/image.rb` (destroying the blob)

We should consider if we want to support this and handle any exceptions gracefully for the user.

**Comment by kevindew** [comment]
I see this as a situation where it'd be ok to serve a user a 500 error in the same vein as if we have a database access error.

The distinctions between this and some of our internal web services is:

- It's easy to be an environment without access to our services (heroku, dev)
- We know from logs it's quite frequent that our services can return an error or timeout

Both of these should not be the case with S3 as we have the local option for the first situation and we expect S3 to have availability.

So I'd think that this is only something to consider coding for if we discover the frequency of the problems is sufficient that they cause a problem.

**Comment by benthorner** [comment]
@kevindew nice argument - I'm happy to close :-).
