### ISSUE TITLE
`rake jasmine:ci` failing on focus tests

### ISSUE THREAD

**Issue by benthorner** [alphagov/content-publisher#702]
Since moving to using Selenium+Chrome, we've had issues with tests that involve the focus/blur events. It looks like some tests have been added that exhibit this same issue, and which are now causing `rake` to fail locally. Can we take another look at these tests to get `rake` working again?

https://stackoverflow.com/questions/29734701/feign-focus-in-selenium-chrome-browser

**Comment by alex-ju** [comment]
Thanks for raising this @benthorner. I'll look into it.

**Comment by benthorner** [comment]
Looks like this isn't happening on CI because it's running on a different OS and version of chromedriver. Unfortunately, trying to upgrade seems to cause it to stop working entirely :-(.

**Comment by benthorner** [comment]
Fixed by https://github.com/alphagov/content-publisher/pull/777.
