### ISSUE TITLE
Our controllers are long and we're not sure where to move the code

### ISSUE THREAD

**Issue by kevindew** [alphagov/content-publisher#740]
## Context

The actions in our controllers have become rather long in a [number](https://github.com/alphagov/content-publisher/blob/1eb067d35d557982f05601cde33c93f9ebea5694/app/controllers/images_controller.rb#L55-L101) [of](https://github.com/alphagov/content-publisher/blob/1eb067d35d557982f05601cde33c93f9ebea5694/app/controllers/documents_controller.rb#L45-L83) [places](https://github.com/alphagov/content-publisher/blob/1eb067d35d557982f05601cde33c93f9ebea5694/app/controllers/contacts_controller.rb#L12-L49). Testing them too can be rather verbose with lots of distinct feature tests: [1](https://github.com/alphagov/content-publisher/blob/1eb067d35d557982f05601cde33c93f9ebea5694/spec/features/workflow/delete_draft_after_publishing_spec.rb), [2](https://github.com/alphagov/content-publisher/blob/1eb067d35d557982f05601cde33c93f9ebea5694/spec/features/workflow/delete_draft_asset_manager_down_spec.rb), [3](https://github.com/alphagov/content-publisher/blob/1eb067d35d557982f05601cde33c93f9ebea5694/spec/features/workflow/delete_draft_publishing_api_down_spec.rb), [4](https://github.com/alphagov/content-publisher/blob/1eb067d35d557982f05601cde33c93f9ebea5694/spec/features/workflow/delete_draft_spec.rb).

We can anticipate that our controller needs are likely to grow rather than shrink in future for the following reasons:

- [We let users access pages they shouldn't have access to](https://trello.com/c/eAGtt4ry/322-we-dont-enforce-our-view-restrictions-in-our-controllers)
- [We raise 500 errors when users perform actions they shouldn't](https://github.com/alphagov/content-publisher/blob/1eb067d35d557982f05601cde33c93f9ebea5694/app/controllers/review_controller.rb#L41), this shouldn't be an internal server error
- We are expecting to add access limiting functionality
- We are hoping to iterate further on permissions

We want to avoid our controllers becoming hugely complicated as [has managed to occur in Whitehall](https://github.com/alphagov/whitehall/blob/27f205b6c3d151e2895c40053fc35645f31e1687/app/controllers/admin/editions_controller.rb)

The natural place for us to move our code would be services. However we've already collectively identified that [our services directory is a mess](https://trello.com/c/f1QaCH7x/231-our-services-directory-is-a-mess) - with it becoming a bundle of various types of utility classes.

## Objectives

I'm hoping that this piece of work can help us work out how a few things:

- If we are to move code out of controllers where does it go? and what is a consistent approach?
- What does belong in our services directory? what consistency can be applied?
- For code that doesn't belong in controllers or services where does it belong? what is our equivalent of a `lib` directory?
- Make decisions in a way that respects idioms of Rails and isn't too surprising for other GOV.UK developers

If it transpires that controllers and services is too broad a scope we'll maybe reduce this in scope.

## Controllers/Actions

We have two distinct kinds of actions in our controllers, which can effectively be split between read (GET) and write (POST/PUT/DELETE) requests that we handle quite differently.

Concerns we'd like to resolve for a common document related read request could be:

- Does a current edition/document exist?
- Should the user have access to the edition?
- Is the edition in an appropriate state for the resource they're requesting?
- Does the user have the appropriate permission to access the resource?
- Did an external service fail to give us the information we need to return the request?

Whereas on a common document related write request we may ask the above questions and more:

- Was the resource changed before the user submitted their request?
- Have we received the parameters we expected?
- Is the users input valid?
- Did we perform their operation successfully?
- How do we present the results of their request?

For these sorts of questions it's worth working out which of these should be before_action, globally handled exceptions and what's part of an actual action.

An approach, that makes sense to me would be to focus a controller action on the handling of the HTTP response that is specific to that action. Where the process to get to that point is handled in an external class that is coupled to the action, but can be tested in isolation. 

A somewhat contrived example is:

```ruby
# frozen_string_literal: true

class ImagesController < ApplicationController
  # ...
  def update
    # Handled with before_action
    # * user not signed in - redirect to login

    UpdateImageAction.new.call(params, current_user) do |result|
      # Handled via exceptions caught in ApplicationController
      # * Document doesn't exist - 404 (ActiveRecord::RecordNotFound)
      # * User hasn't got access to Document/Edition - 403
      # * Edition isn't editable - 302 to summary page

      # Maybe controller level or route - be nice if we could get rid
      # * GdsApi::BaseError

      result.failure :requirements do |document, image_revision, issues|
        @document = document
        @image_revision = image_revision

        flash.now["alert_with_items"] = {
          "title" => I18n.t!("documents.edit.flashes.requirements"),
          "items" => issues.items,
        }

        render :edit, status: :unprocessable_entity
      end

      # Potential item
      result.failure :conflict do |document, image_revision, conflict|
        @document = document
        @image_revision = image_revision

        render :edit, status: :conflict, conflict: conflict
      end

      result.success do |document, image_revision|
        notice = if params[:wizard] == "lead_image"
                   t("documents.show.flashes.lead_image.added", file: image_revision.filename)
                 else
                   t("images.index.flashes.details_edited", file: image_revision.filename)
                 end
        redirect_to images_path(document), notice: notice
      end
    end
  end
end
```

## Services

Currently our services directory contains a variety of things.

We have some which do a single thing - I call these transactions based on [dry-transaction](https://dry-rb.org/gems/dry-transaction/) - and act like a [pure-function-as-an-object](https://www.tomdalling.com/blog/ruby/pure-function-as-an-object-PFAAO-pattern/).

Some examples of these are: [DeleteDraftService](https://github.com/alphagov/content-publisher/blob/1eb067d35d557982f05601cde33c93f9ebea5694/app/services/delete_draft_service.rb), [ImageDeleteService](https://github.com/alphagov/content-publisher/blob/1eb067d35d557982f05601cde33c93f9ebea5694/app/services/image_delete_service.rb), [PathGeneratorService](https://github.com/alphagov/content-publisher/blob/1eb067d35d557982f05601cde33c93f9ebea5694/app/services/path_generator_service.rb), [PublishService](https://github.com/alphagov/content-publisher/blob/master/app/services/publish_service.rb)

These are probably all things that could be described with a verb.

Then we have a collection that are used as repositories or adapters to data. Examples: [AssetManagerService](https://github.com/alphagov/content-publisher/blob/1eb067d35d557982f05601cde33c93f9ebea5694/app/services/asset_manager_service.rb), [LinkablesService](https://github.com/alphagov/content-publisher/blob/1eb067d35d557982f05601cde33c93f9ebea5694/app/services/linkables_service.rb), [TopicIndexService](https://github.com/alphagov/content-publisher/blob/1eb067d35d557982f05601cde33c93f9ebea5694/app/services/topic_index_service.rb)

Finally we have the more utility class that have probably ended up in services since they have no natural home. Examples of these are: [GovspeakDocument](https://github.com/alphagov/content-publisher/blob/1eb067d35d557982f05601cde33c93f9ebea5694/app/services/govspeak_document.rb), [EditionFilter](https://github.com/alphagov/content-publisher/blob/1eb067d35d557982f05601cde33c93f9ebea5694/app/services/edition_filter.rb), and [Requirements module](https://github.com/alphagov/content-publisher/tree/1eb067d35d557982f05601cde33c93f9ebea5694/app/services/requirements).

We also have some inconsistent naming with some classes suffixed with Service others not.

## Sources of inspiration

Our best way to not create a surprising solution is to build on the work of others.

Gems I've identified that try to solve similar problems to our controllers are:

- [dry-transaction](https://dry-rb.org/gems/dry-transaction/)
- [Trailblazer operation](http://trailblazer.to/gems/operation/2.0/)
- [interactor](https://github.com/collectiveidea/interactor)

Patterns used in GOV.UK:

- [Commands in Publishing API](https://github.com/alphagov/publishing-api/blob/0aebd7faa3608bf8b9eb8ee68da74185b19544bb/app/commands/v2/put_content.rb)
- [Email Alert API approach to services](https://github.com/alphagov/email-alert-api/blob/2c8c3a70e479c1af4fe440bce6f622de5040d1cd/app/controllers/notifications_controller.rb#L3-L10)

## Next steps

This issue is intended to start the ball rolling on this by trying to provide a place to ask questions or post ideas. You may want to use this an opportunity to look at parts of our code to decide if you agree that we have the issues outlined here and what approaches could be used to solve them. Then we'll probably look at having a dev chat and looking at areas we can prototype/experiment with.

Using a Github issue to start the conversation on this is a new approach to me, so interested to see how it goes. Feedback welcome.

**Comment by benthorner** [comment]
@kevindew this makes sense to me on first reading, except the 'rule of thumb'. Could you try and re-phrase that paragraph, maybe adding an example, as it's a bit too abstract for me?

**Comment by kevindew** [comment]
@benthorner Sure thing - just re-phrased and added an example.

**Comment by kevindew** [comment]
I've put together a couple of prototypes using popular libraries for this type of problem. I'm interested to see what you all think and to see where we can start taking this.

# Using interactor gem

[Interactor](https://github.com/collectiveidea/interactor) as a gem has been around since 2013 and looks healthy on [ruby-toolbox](https://www.ruby-toolbox.com/projects/interactor). Do have a read of the documentation, it's use case examples are very similar to our goals.

I had a play with rewriting one of the [ImageController](https://github.com/alphagov/content-publisher/blob/d8e317c9231b4779f5de5cb5827a42a50e1e38b0/app/controllers/images_controller.rb#L13) actions with this. I came out with a controller action that looked like:

https://github.com/alphagov/content-publisher/blob/57e85fe24b916b66442a0536c77eb91791a49f0e/app/controllers/images_controller.rb#L13-L25

With an action/service class: https://github.com/alphagov/content-publisher/blob/57e85fe24b916b66442a0536c77eb91791a49f0e/app/actions/create_image_action.rb

Whole commit: https://github.com/alphagov/content-publisher/commit/57e85fe24b916b66442a0536c77eb91791a49f0e

What I found cool about interactor was:

- really flexible
- pretty much designed for our Rails use case
- didn't force any code paradigms so was easy to use with code that feels idiomatic for GOV.UK
- has patterns (organizers) for dealing with more complex cases

What wasn't so nice:

- isn't very clear what required parameters for an interactor are
- it feels a little hacky assigning lots of stuff to attributes of a context object

# Using dry-transaction gem

[dry-transaction](https://dry-rb.org/gems/dry-transaction/) is part of the [dry-rb](https://dry-rb.org/) family of gems that have gained popularity in the Ruby world by bringing a number of functional programming paradigms to Ruby. Dry-transaction is a set of classes for isolating business transactions from other code.

This time I had a play with the [DocumentController#update](https://github.com/alphagov/content-publisher/blob/d8e317c9231b4779f5de5cb5827a42a50e1e38b0/app/controllers/documents_controller.rb#L45-L83) action. I came out with an action that looked like this:

https://github.com/alphagov/content-publisher/blob/f9277ad736166b73ab83d8facfa3b498e4127bcd/app/controllers/documents_controller.rb#L45-L64

With an action/service class of: https://github.com/alphagov/content-publisher/blob/f9277ad736166b73ab83d8facfa3b498e4127bcd/app/actions/update_edition_action.rb

Whole commit: https://github.com/alphagov/content-publisher/commit/f9277ad736166b73ab83d8facfa3b498e4127bcd

What I found cool about dry-transaction was:

- It seems really well suited to scaling to more complex and re-usable scenarios
- By clearly defining all steps inputs and outputs the code is really clear
- In theory the steps would be very easy to test based on their rigid interfaces
- It was nice handling everything in a block, though this lead to a bit of end end end end nesting at the end

What wasn't so nice:

- Steeper learning curve than interactor
- Passing parameters around becomes a bit tedious due to lack of shared state.

# On reflection

I came into this with quite high expectations of dry-transaction, as I'd heard good things about the collection of libraries, but for the use case I had it felt pretty heavy duty for the job I'd given it. I came away pleasantly surprised with interactor, as it felt simple and quick to put something together and was pleased with how it's purpose was so similar to our goals.

/cc @emmabeynon @1pretz1 @benthorner

**Comment by benthorner** [comment]
I thought I'd write this here, as it's not specific to the Interactor approach we're currently investigating in https://github.com/alphagov/content-publisher/pull/893. The versioning work introduced pessimistic locking into the app, which means we have a lot of code of the form `Edition.find_and_lock_current(*args) { block }`.

While the use of pessimistic locking with Edition is superficially quite simple, the reality is much more subtle. Myself and @1pretz1 spent quite a long time building our knowledge of how the locking works in order to identify potential solutions to a bug with notifications.

```
Edition.find_and_lock_current(*args) do |edition|
  # check !edition.live?
  # publish the document
  # create TimelineEntry
  # send notifications - does remote calls that might fail and cause rollback :-|
end
```

The temptation here is to think that the whole block is somehow 'locked' and that it would be 'bad' to move code outside of it, where the `edition` variable is also unhelpfully unavailable. After some investigation, we realised there's an implicit pattern to how we do our locking:

```
Edition.find_and_lock_current(*args) do |edition|
  # pre-op (setup and check)
  # do any setup e.g. create a new revision
  # do a check to make sure we continue e.g. !edition.live?

  # op (change state and release)
  # change the state e.g. call Publishing API
  # edition.save!

  # post-op (finish, redirect)
  # non-critical code e.g. PreviewService
  # redirect_to document_path
end
```

What's initially hard to understand is the interaction between the lock, the pre-op check and the op itself. It's now clear that the lock causes the code to stop executing if another lock is already held on the edition, while the executing the op code makes sure the pre-op check fails.

The pain point here was learning that the lock is no longer active by the time we get to the post-op code, so there is no loss in integrity if we move the post-op code outside of the transaction; superficially the `find_and_lock_current` method implies the whole block is locked.

```
edition = Edition.find_and_lock_current(*args) do |edition|
  ...
  # make sure we use 'return' instead of 'next'
end

# post-op
```

Another alternative is to wrap the flakey post-op code in a non-joinable transaction, which protects the outer transaction from rollback: `Edition.transaction(joinable: false) { post-op }`.

## The Key Point

The above is mostly to provide context :-). As we improve our controllers, we think it's worth trying to make the structure of our locking/transactions more concrete, so that it's easier to write new ones that implement locking correctly and make it easier to incorporate post-op code.

**Comment by kevindew** [comment]
We're now using the interactor gem in our controllers as per: https://github.com/alphagov/content-publisher/pull/960 

This closes this issue. There is still an ADR to come which records the decisions around this.

**Comment by benthorner** [comment]
@kevindew 👍. One question I had was how we decide which actions should be in an interactor? I noticed the NewDocumentController is unchanged - looks like there are reasons in both directions there.

**Comment by kevindew** [comment]
@benthorner My rules would be (using RFC 2119 terminology: https://tools.ietf.org/html/rfc2119)

For post/put/delete requests that mutate DB state an interactor SHOULD be used. By that `NewDocumentController#create` is an oversight

For all other requests an Interactor MAY be used. They don't really feel like they'd add benefit to `NewDocumentController#choose_document_type` for instance. I also think they'd be a good addition for a long GET with filtering.

Does that help? I imagine there are scenarios that don't quite justify an Interactor being a MUST.

**Comment by benthorner** [comment]
Ah, the 'shouty case' RFC ;-). That's helpful - it was the #create action that made me wonder, anyway!
